language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master
script:
  - cargo test
  - cargo test --features preserve_order
  - cargo test --manifest-path test-suite/Cargo.toml
  - rustdoc --test README.md -L target
notifications:
  email:
    on_success: never
